#@ load("@ytt:data", "data")

#@ def target_rolebinding(role, rolebindings):
#@   for rolebinding in rolebindings:
#@     if rolebinding.role.name == role:
#@       return rolebinding
#@     end
#@   end
#@   return None
#@ end

#@ role = "ns-admin"
#@ rolebinding = target_rolebinding(role, data.values.rbac.rolebindings)
#@ for/end namespace in rolebinding.namespaces:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: #@ role
  namespace: #@ namespace.name
rules:
- apiGroups: [ "*" ]
  resources: [ "*" ]
  verbs: [ "*" ]