#@data/values
---
rbac:
  rolebindings:
  - role:
      kind: Role
      name: ns-admin
    namespaces: []
    users: []
    groups: []
    serviceaccounts: []
  clusterrolebindings:
  - role:
      name: admin
    users: []
    groups: []
    serviceaccounts: []

#! Example
#! rbac:
#!   rolebindings:
#!   - role:
#!       kind: Role
#!       name: ns-admin
#!     namespaces:
#!     - name: ns1
#!       create: true
#!     - name: ns2
#!     users:
#!     - name: user1
#!     - name: user2
#!     groups:
#!     - name: developers
#!     serviceaccounts:
#!     - name: ci-bot
#!   clusterrolebindings:
#!   - role:
#!       name: admin
#!     users:
#!     - name: admin
#!     groups:
#!     - name: administrators
#!     serviceaccounts:
#!     - name: admin-bot
#!       namespaces:
#!       - name: ns1
#!       - name: ns2